### ISSUE TITLE
Research smoking and insufflation

### ISSUE THREAD

**Issue by sandypreiss** [RTIInternational/virtual-opioid-user#11]
To decide if we need to separate PK function from injection, or can just use one for all. If less than 15 minutes to take effect, don't need to separate from injection.

**Comment by berghammeraj** [comment]
Found no significant differences between smoking/insufflation/injecting for heroin:

Smoking: https://www.researchgate.net/publication/15374759_Pharmacokinetics_and_Pharmacodynamics_of_Smoked_Heroin

Insufflation:
https://www.researchgate.net/publication/14927071_Pharmacokinetics_and_Pharmacodynamics_of_Intranasal_Snorted_Heroin
