### ISSUE TITLE
Option 1 version: use output of will_increase_dose to adjust dose taking behavior via params passed to record_dose_taken 

### ISSUE THREAD

**Issue by berghammeraj** [RTIInternational/virtual-opioid-user#19]
Blocked by: https://github.com/RTIInternational/virtual-opioid-user/issues/18

Ex. If going to dealer before, going to dealer later, adjust doses/drugs/etc. accordingly 

A person "supply" attribute would be one way to handle this. E.g., after exhausting their prescription, they go to dealer

**Comment by sandypreiss** [comment]
Decision on how to implement this - use a simple version (option 1) for now, then add more complex version (option 3) later.

**Comment by sandypreiss** [comment]
![image](https://user-images.githubusercontent.com/54412843/172891809-5d787979-7a09-4474-8a97-c30cac6b5b78.png)
